apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  # advertiseAddress: 192.168.0.213
  advertiseAddress: 192.168.179.41
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.22.0
networking:
  podSubnet: 10.244.0.0/16 # --pod-network-cidr
clusterName: "ddt"
