version: '3'
networks:
  ddt-network:
    external: false
    driver: "bridge"
services:
  ddt-manager:
    image: inspiron:5000/ddt-manager:latest
    ports:
      - 4444:1234
    environment:
      - FLASK_ENV=development
      - DDT_FOLDER=/ddt
      - DDT_PROBE_SERVER_PORT=4000
    networks:
        - ddt-network

  ddt-probe-1:
    image: inspiron:5000/ddt-demo:latest
    ports:
      - 4001:4000
    environment:
      - DDT_FOLDER=/ddt
      - DDT_PROBE_SERVER=ddt-probe-1
      - DDT_PROBE_SERVER_PORT=4000
      - APP_ID=chatter-test
      - POD_ID=ddt-probe-1
      - POD_IP=ddt-probe-1
      - ROS_DOMAIN_ID=42
      - DDT_MANAGER_SERVER=ddt-manager
      - DDT_MANAGER_PORT=1234
    networks:
        - ddt-network
    command:
      bash -c "
      source /ros_entrypoint.sh &&
      ros2 launch lifecycle_chat scenario1.py & ./run.sh"
    depends_on:
      - ddt-manager
