version: '3'

services:
  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.cert
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - $HOME/registry:/var/lib/registry
      - $HOME/registry_certs:/certs

