apiVersion: v1
kind: Service
metadata:
  name: ddt-probe-service
  labels:
    role: ddt-probe
spec:
  # Start a headless service
  # https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  clusterIP: None
  ports:
    - name: server-port
      port: 4000
      targetPort: 4000
      protocol: "TCP"
  selector:
    role: ddt-probe
