apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatter-galactic-talker
  labels:
    app: chatter-galactic
    node: talker
    namespace: chatter
spec:
  replicas: 1
  selector:
    matchLabels:
      node: talker
  template:
    metadata:
      labels:
        node: talker
      annotations:
        k8s.v1.cni.cncf.io/networks: rosmc-network
    spec:
      containers:
      - name: chatter-galactic-talker
        image: inspiron:5000/chatterpy:galactic
        args:
          - "ros2"
          - "launch"
          - "chatter_py"
          - "talker.launch.py"
        # command: ["/bin/bash", "-c"]
        # args: ["source /opt/ros/galactic/setup.bash && ros2 topic pub /chatter std_msgs/String \"data: Hello ROS Developers\""]
        env:
            -
              name: ROS_DOMAIN_ID
              value: "42"
            -
              name: NETINTERFACE
              value: "net1"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        ports:
            - containerPort: 8000
      # nodeSelector:
      #       machine: samsung
---
apiVersion: v1
kind: Service
metadata:
  name: service-talker
  labels:
    app: chatter-galactic
    node: talker
    namespace: chatter
spec:
  # Start a headless service
  # https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  clusterIP: None
  ports:
    - port: 8000
  selector:
    node: talker
