apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatter-galactic-pub
  labels:
    app: chatter-galactic-pub-echo
    node: pub
    namespace: pub-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      node: pub
  template:
    metadata:
      labels:
        node: pub
      annotations:
        k8s.v1.cni.cncf.io/networks: rosmc-network
    spec:
      containers:
      - name: chatter-galactic-pub
        image: rachelwu/ros:galactic
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/galactic/setup.bash && ros2 topic pub /chatter std_msgs/String \"data: Hello ROS Developers\""]
        env:
            -
              name: ROS_DOMAIN_ID
              value: "42"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      nodeSelector:
            machine: sebastian-thinkpad-s1-yoga-12
---
apiVersion: v1
kind: Service
metadata:
  name: service-pub
  labels:
    app: chatter-galactic-pub-echo
    node: pub
    namespace: pub-echo
spec:
  # Start a headless service
  # https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  clusterIP: None
  ports:
    - port: 8000
  selector:
    node: pub
