apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: chatter-demo
    role: ddt-probe
  name: ddt-debug-chatter-demo-tnode1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatter-demo
      role: ddt-probe
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chatter-demo
        role: ddt-probe
      # annotations:
      #   k8s.v1.cni.cncf.io/networks: rosmc-network
    spec:
      containers:
      - name:  ddt-debug-chatter-demo-tnode1
        image: inspiron:5000/ddt-demo:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: ["
              source /ros_entrypoint.sh && ros2 launch lifecycle_chat tnode.py &
              source /ros_entrypoint.sh && ros2 lifecycle set /debug_tnode1 configure &&
              source /ros_entrypoint.sh && ros2 lifecycle set /debug_tnode1 activate &&
              source /ros_entrypoint.sh && ./run.sh
              "
              ]
        env:
          - name: POD_ID
            value: ddt-debug-chatter-demo-tnode1
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DDT_FOLDER
            value: /ddt
          - name: DDT_PROBE_SERVER
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DDT_PROBE_SERVER_PORT
            value: "4000"
          - name: APP_ID
            value: chatter-demo
          - name: ROS_DOMAIN_ID
            value: "10"
          - name: DDT_MANAGER_SERVER
            value: ddt-manager
          - name: DDT_MANAGER_PORT
            value: "1234"
          - name: NETINTERFACE
            value: "lo"
          - name: CYCLONEDDS_URI
            value: file:///root/dds_setting.xml
          - name: RUST_LOG
            value: INFO
        ports:
          - containerPort: 4000
